### PR TITLE
Use emojis to share result ⬜🟨🟧🟥🟩

### PR DESCRIPTION
**Pull request by olliechick**
This addresses part of #1 

Share text now looks like:

> 🌎 Feb. 6, 2022 🌍
Today's guesses: ⬜⬜⬜⬜⬜⬜🟨🟧🟧🟧🟧🟧🟧🟥🟫🟫🟫🟩
Current streak: 1
Average guesses: 18
>
> https://globle-game.com

_Edit: for reference, this is the current share text:_

> 🌎 Feb. 6, 2022 🌍
Today's guesses: 11
Current streak: 1
Average guesses: 11
>
> https://globle-game.com

_Edit 2: This is what I have changed it to look like:_
> Globle 6 Feb 2021
🔥1 | Average score: 18.4
⬜⬜⬜⬜⬜⬜🟧🟨
🟧🟧🟧🟧🟧🟥🟥🟧
🟥🟥🟩

### CODE REVIEW

**Comment by the-abe-train** [comment]
Thank you for contributing! I have 2 notes on this potential update:
1. Brown isn't really a colour in the game, and that would look confusing. It should be combined with red, and the colour percentile redistributed.
2. This would create a lot of text for players that use many guesses, and I want to make sure people have enough space in their tweets for additional comments. I think the following would look a little cleaner:
> 🌎 Feb. 6, 2022 🌍
6⬜ 1🟨 6🟧 4🟥 1🟩 
Current streak: 1
Average guesses: 18

I'm not sure that's the _optimal_ solution though. Let me know what you think.

**Comment by olliechick** [comment]
1. What do you think is a good percentile distribution?

2. With that, you lose the order that each colour was guessed in. What about simply:
> Globle 6 Feb 2022
> ⬜⬜⬜⬜⬜⬜🟧🟨🟧🟧🟧🟧🟧🟥🟥🟧🟥🟥🟩

**Comment by IanDLacy** [comment]
I'd like to throw my two cents in here:

I like this idea. I don't like the brown either. I prefer the sequence approach over the histogram approach. I'm also concerned about the number of characters, but primarily how they are laid out. Here's my suggestion for more of how I think it should look, with some additional changes:

🌎  https://globle-game.com/
Streak: 1
Avg: 18
2/6: 19
⬜⬜⬜⬜⬜⬜🟧🟨
🟧🟧🟧🟧🟧🟥🟥🟧
🟥🟥🟩⬛⬛⬛⬛⬛

The above is 144 bytes in UTF-8 and looks a lot cleaner in my opinion. Some further omissions could be made such as the black squares being used as filler, for example. Somewhat combining the previous two posted ideas results in a kind of lossless compression:

🌎  https://globle-game.com/
Streak: 1
Avg: 18
2/6: 19
6⬜ 🟧 🟨 5🟧 2🟥 🟧 2🟥 🟩

This second example conveys the same information as the first, and is 99 bytes in UTF-8. Stripping out all spaces drops it down to 88 bytes, but it doesn't look as clean. We can take it even further, but that would be venturing into unintuitive territory. As it stands, these examples I've provided, or something along these lines, are roughly equivalent to Wordle output, which is 128 bytes in UTF-8 at largest. Also keep in mind, the end user can always strip off the URL and perform other reformatting to their liking if they feel the need.

**Comment by rubybrowncoat** [comment]
I personally like the first option proposed by @IanDLacy the most.

**Comment by IanDLacy** [comment]
A yet more visually compact option at 104 bytes UTF-8, and without a date because it's obvious from wherever this would be posted.

🌎 https://globle-game.com/
Streak: 1 | Avg: 18 | Today: 19
6⬜ 🟧 🟨 5🟧 2🟥 🟧 2🟥 🟩

**Comment by olliechick** [comment]
What about using the emoji 🔥 to represent streaks, removing the average, and breaking it down into rows of 5 so it is easy to scan and count? I think the date should be kept so you can easily compare to people in different timezones who might have a different country.

> Globle 6 Feb 2021
> 🔥1
> ⬜⬜⬜⬜⬜
> ⬜🟧🟨🟧🟧
> 🟧🟧🟧🟥🟥
> 🟧🟥🟥🟩

**Comment by IanDLacy** [comment]
I like the average as it kind of serves as a 'level', and I worry about over-symbolizing things, but I do think the 'fire' for streak is fun. Super solid point about the date though! I think rows of 5 is too 'wordle-y', and I'm quite the fan of 8 being not too big and not too small.

Speaking of the numbers, what is the 'lose' condition of this game? I haven't jumped into the code yet, but I did a crude test and it seems like it is impossible to lose. 16 seemed like a good lower boundary to me, but I gave up the test when I hit 32. I have been playing for several days now, and I'm pretty bad at geography, but my average is still under 8. Seems like there should be a limit well below 195 or however many countries there are. That's a lot of squares to share in this edge case lol.

**Comment by olliechick** [comment]
Yeah, that's a good point on the 8. Maybe something like this:

> Globle 6 Feb 2021
🔥1 | Average score: 18.4
> ⬜⬜⬜⬜⬜⬜🟧🟨
🟧🟧🟧🟧🟧🟥🟥🟧
🟥🟥🟩

I think the 'lose' condition is just the player not finding the country - I don't think there's an upper limit to guesses.

**Comment by olliechick** [comment]
I've implemented my above suggestion

**Comment by IanDLacy** [comment]
Ok so with all of this in mind, I revise my suggestion to be:

🌎 https://globle-game.com/
🔥 1 | Avg 18 | 2/6
⬜⬜⬜⬜⬜⬜🟧🟨
🟧🟧🟧🟧🟧🟥🟥🟧
🟥🟥🟩

124 bytes, but I would also suggest cutting it off at 16 guesses.

**Comment by rubybrowncoat** [comment]
I think 16 is going to be too low of a cutoff, a few people I play with have averages in the high teens low twenties. I would suggest 24 or even 32

**Comment by olliechick** [comment]
I think my solution is the best combination of conciseness and clarity. @the-abe-train what are your thoughts?

**Comment by the-abe-train** [comment]
In light of Facebook banning the Globle URL in posts, I think it's time to implement this change. I still think that the following format is the best:

> 🌎 Feb. 6, 2022 🌍
6⬜ 1🟨 6🟧 4🟥 1🟩 
Current streak: 1
Average guesses: 18
> 
> #Globle


It doesn't bother me that the order of guesses is lost, I think having the order makes the text too messy and crowded. Also, I prefer not to use the browser's locale for the date formatting; everyone's sharing message should have the same date format so that people can quickly see that they are comparing the same day's scores. Finally, given that we can't use the URL anymore, let's use a hashtag instead.

@olliechick if you update your pull request to meet this format, I'll merge it.

**Comment by rubybrowncoat** [comment]
> It doesn't bother me that the order of guesses is lost, I think having the order makes the text too messy and crowded. 

I couldn't disagree more. The progression is what gives your guesses (and their colors) actual meaning, it maps your "journey" so to speak and makes it plain to others. That seems to be what is missing from sharing your day's play. I feel losing that would leave it an emotionless list of wrong guesses, ordered by degree. It'd be better than just the number but it misses the mark by quite a bit.

I hope you reconsider.

**Comment by the-abe-train** [comment]
@rubybrowncoat "Emotionless" is a strong word... but you make a fair point. Upon reconsideration, I will accept either format.

@olliechick I want to merge this branch by EOD Monday (EST), so if you want to make any changes to your PR, then please do so soon. Otherwise, I will merge it as it is.

I appreciate the community feedback on this change. Thank you all for taking an interest in improving the game!

**Comment by olliechick** [comment]
I've taken off the commit that changes the date formatting, but I've left the other commit as it

**Pull request merged**
